In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("C:/Users/meetp/Downloads/!PYTHON FILES/hotel_reviews")

df.drop(df.columns[0], axis=1, inplace=True)
df.head()

In [ ]:
from src.components.data_tranformation import DataTransformation
from src.components.model_trainer import ModelTrainer 


data_transformation = DataTransformation()
X_balanced, y_balanced = data_transformation.transform(df)
            
print(X_balanced)

In [ ]:
y_balanced.values

In [ ]:
model_trainer = ModelTrainer()
gru, X_test, y_test = model_trainer.train_model(X_balanced, y_balanced)

In [ ]:
import numpy as np

y_pred = np.argmax(gru.predict(X_test),axis = 1)
y_pred

In [ ]:

from sklearn.metrics import classification_report, confusion_matrix

loss, accuracy = gru.evaluate(X_test, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

print(classification_report(y_test, y_pred))
print("Classification Report:")

print(confusion_matrix(y_test, y_pred))
print("Confusion Matrix:")

In [2]:
import pandas as pd

df = pd.read_csv("C:/Users/meetp/Downloads/!PYTHON FILES/hotel_reviews")

df.drop(df.columns[0], axis=1, inplace=True)
df.head()

Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [3]:
X = df['Review']
y = df['Rating'] - 1

In [4]:
from src.utils.utils import load_object, load_GRU

preprocess = load_object('artifacts/GRU_Preprocessor.pkl')
loaded_model = load_GRU('artifacts/GRU_Model.h5')

Model loaded successfully from artifacts/GRU_Model.h5


In [5]:
X_padded = preprocess.transform(X)
X_padded

array([[   0,    0,    0, ...,  177,  216,    8],
       [   0,    0,    0, ...,  794,    1,  516],
       [   0,    0,    0, ...,   42, 1665,   83],
       ...,
       [   0,    0,    0, ...,  390, 1464,  999],
       [   0,    0,    0, ...,  320, 4658, 3646],
       [   0,    0,    0, ...,  157,  125,   20]])

In [12]:
from sklearn.model_selection import train_test_split

X_subset, _, y_subset, _ = train_test_split(X_padded, y, train_size=100, stratify=y)

In [13]:
import numpy as np

y_pred = np.argmax(loaded_model.predict(X_subset),axis = 1)
y_pred

4/4 [==============================] - 0s 91ms/step


array([1, 3, 3, 3, 4, 2, 3, 3, 4, 4, 4, 4, 3, 0, 1, 1, 3, 2, 3, 4, 1, 4,
       3, 4, 3, 2, 4, 4, 3, 4, 4, 4, 2, 4, 3, 1, 3, 4, 3, 3, 4, 4, 4, 3,
       3, 0, 2, 4, 4, 4, 4, 4, 3, 4, 3, 4, 4, 3, 0, 0, 4, 4, 3, 4, 4, 2,
       4, 1, 2, 3, 3, 1, 3, 1, 4, 1, 3, 4, 3, 3, 4, 4, 4, 4, 3, 2, 4, 0,
       1, 0, 4, 3, 4, 2, 4, 0, 4, 3, 4, 4], dtype=int64)

In [14]:
y_subset.values

array([1, 3, 3, 3, 4, 2, 3, 4, 4, 4, 4, 4, 4, 0, 3, 1, 3, 2, 3, 4, 1, 4,
       3, 2, 3, 2, 4, 4, 3, 4, 4, 4, 2, 4, 3, 1, 3, 4, 3, 3, 4, 4, 4, 4,
       4, 0, 2, 4, 4, 4, 4, 3, 3, 3, 3, 4, 4, 3, 0, 0, 4, 4, 3, 4, 4, 2,
       4, 1, 2, 3, 3, 1, 3, 1, 4, 1, 3, 4, 3, 2, 4, 4, 4, 4, 3, 2, 4, 0,
       1, 0, 4, 3, 4, 2, 4, 0, 3, 3, 4, 4], dtype=int64)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

loss, accuracy = loaded_model.evaluate(X_subset, y_subset)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

print(classification_report(y_subset, y_pred))
print("Classification Report:")

print(confusion_matrix(y_subset, y_pred))
print("Confusion Matrix:")

4/4 [==============================] - 0s 57ms/step - loss: 0.2688 - accuracy: 0.9000
Test Loss: 0.2687566876411438, Test Accuracy: 0.8999999761581421
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.90      1.00      0.95         9
           2       1.00      0.82      0.90        11
           3       0.83      0.86      0.85        29
           4       0.91      0.91      0.91        44

    accuracy                           0.90       100
   macro avg       0.93      0.92      0.92       100
weighted avg       0.90      0.90      0.90       100

Classification Report:
[[ 7  0  0  0  0]
 [ 0  9  0  0  0]
 [ 0  0  9  1  1]
 [ 0  1  0 25  3]
 [ 0  0  0  4 40]]
Confusion Matrix:
